

export const CART_PRODUCT_REQUEST = 'CART_PRODUCT_REQUEST';
export const CART_PRODUCT_SUCCESS = 'CART_PRODUCT_SUCCESS';
export const CART_PRODUCT_FAILED = 'CART_PRODUCT_FAILED';

export const PRODUCT_ADD_CART_REQUEST = 'PRODUCT_ADD_CART_REQUEST';

export const PRODUCT_REMOVE_FROM_CART = 'PRODUCT_REMOVE_FROM_CART';

export const INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY';
export const DECREMENT_PRODUCT_QUANTITY = 'DECREMENT_PRODUCT_QUANTITY';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';
